from setuptools import setup

setup(name='pynewtonmath',
      version='1.0.1',
      description='Python 3 wrapper for the Newton math API',
      url='https://github.com/benpryke/PyNewtonMath',
      author='Benjamin Pryke',
      author_email='benprykedev@gmail.com',
      license='MIT',
      classifiers=['Development Status :: 5 - Production/Stable',
                   'Intended Audience :: Developers',
                   'License :: OSI Approved :: MIT License',
                   'Natural Language :: English',
                   'Programming Language :: Python :: 3 :: Only',
                   'Topic :: Software Development :: Libraries :: Python Modules'],
      keywords='newton API REST math maths restful',
      packages=['pynewtonmath'],
      install_requires=[],
      python_requires='>=3',
      zip_safe=False)
